from flask import Flask, jsonify, request
import logging
import json
import time

app = Flask(__name__)

# setting up a clean JSON logger
log_file = "login_attempts.jsonl"
logger = logging.getLogger("BankSecurityLogger")
logger.setLevel(logging.INFO)
file_handler = logging.FileHandler(log_file)

# defining what our model will need later
def log_attempt(ip_address, username, status, user_agent):
    log_entry = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "ip_address": ip_address,
        "username": username,
        "status": status,
        "user_agent": user_agent
    }
    # writing the log as a JSON string to our file
    file_handler.stream.write(json.dumps(log_entry) + "\n")
    file_handler.stream.flush()  # ensure it's written to disk

import os
# ... your other imports ...

@app.route('/api/login', methods=['POST'])
def login():
    data = request.get_json()
    username = data.get('username', "")
    password = data.get('password', "")
    
    ip_address = request.headers.get('X-Forwarded-For', request.remote_addr)
    user_agent = request.headers.get('User-Agent', 'Unknown')

    # NEW: Dynamically load the massive database generated by the orchestrator
    VALID_USERS = {}
    if os.path.exists("database.json"):
        with open("database.json", "r") as f:
            VALID_USERS = json.load(f)

    # Dynamic Authentication Logic
    if username in VALID_USERS and VALID_USERS[username] == password:
        log_attempt(ip_address, username, "SUCCESS", user_agent)
        return jsonify({"message": f"Welcome Back, {username}."}), 200
    else:
        log_attempt(ip_address, username, "FAILED", user_agent)
        return jsonify({"message": "Invalid credentials."}), 401
    
if __name__ == '__main__':
    print("[*] Starting Bank API Security Gateway on port 5001...")
    app.run(host='0.0.0.0', port=5001)